// import { Geist, Geist_Mono } from "next/font/google";
import { Satisfy } from "next/font/google";
import "./globals.css";

const satisfy = Satisfy({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-satisfy",
});
// import { Poppins,Inter } from 'next/font/google'

// const poppins = Poppins({
//   subsets: ["latin"],
//   variable: "--font-poppins",
//   weight: ["100","200","300","400","500","600","700","800","900"]
// });

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
//   weight: ["100","200","300","400","500","600","700","800","900"]
// });
// const roboto_flex = Roboto_Flex({
//   weight: ["400","500","600","700","800","900"],
//   subsets: ['latin'],
// })
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${satisfy.variable} h-full antialiased`}
      
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
